version: 2
updates:

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      postgresql:
        patterns:
          - "*postgresql*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
      postgresql:
        patterns:
          - "postgresql*"
          - "*postgresql*"
          - "*postgresql"

  - package-ecosystem: npm
    directory: "/e2e"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript"
        versions: ["5.7.2"]

  - package-ecosystem: npm
    directory: "/cameras-gui"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript"
        versions: ["5.7.2"]

    groups:
      angular:
        patterns:
          - "@angular*"
          - "angular*"
          - "*angular*"
      types:
        patterns:
          - "@types*"
          - "*types*"
