version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "node"
    directory: "/e2e"
    schedule:
      interval: "daily"
