services:
  e2e-electron:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser electron"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-chrome:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser chrome"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-firefox:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser firefox"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-edge:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser edge"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras
