services:
  e2e-electron:
    image: "cypress/included:12.13.0"
    working_dir: /e2e
    command: "--browser electron --config-file cypress.pipeline.config.ts --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-electron-full:
    image: "cypress/included:12.13.0"
    working_dir: /e2e
    command: "--browser electron --config-file full.cypress.config.ts --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
      - ./e2e/cypress/videos:/e2e/cypress/videos
      - ./e2e/cypress/screenshots:/e2e/cypress/screenshots
    networks:
      - healthy-cameras

  e2e-chrome:
    image: "cypress/included:12.13.0"
    working_dir: /e2e
    command: "--browser chrome --config-file cypress.pipeline.config.ts  --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-firefox:
    image: "cypress/included:12.13.0"
    working_dir: /e2e
    command: "--browser firefox --config-file cypress.pipeline.config.ts  --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-edge:
    image: "cypress/included:12.13.0"
    working_dir: /e2e
    command: "--browser edge --config-file cypress.pipeline.config.ts  --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras
