services:
  e2e-electron:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser electron --config-file cypress.pipeline.config.ts --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-chrome:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser chrome --config-file cypress.pipeline.config.ts  --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-firefox:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser firefox --config-file cypress.pipeline.config.ts  --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-edge:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser edge --config-file cypress.pipeline.config.ts  --config baseUrl=http://kong:8000"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras
