services:
  e2e-electron:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser electron --config baseUrl=http://kong:8000/camera-1-service"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-chrome:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser chrome --config baseUrl=http://kong:8000/camera-1-service"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-firefox:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser firefox --config baseUrl=http://kong:8000/camera-1-service"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras

  e2e-edge:
    image: "cypress/included:10.7.0"
    working_dir: /e2e
    command: "--browser edge --config baseUrl=http://kong:8000/camera-1-service"
    volumes:
      - ./e2e:/e2e
    networks:
      - healthy-cameras
