name: HC Build, Test, Coverage and Report

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'adopt'
        - uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Build Node
          run: make build-npm

        - name: Test Node
          run: make test-npm

        - name: Coverage Node
          run: make coverage-npm

        - name: Build and Test MAVEN
          run:  mvn clean install jacoco:prepare-agent package jacoco:report

        - name: Coverage Reports
          run: mvn omni-coveragereporter:report
          env:
             COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
             CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
             CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

        - name: Maven OWASP Security Check
          run: mvn clean install -Powasp
