name: HC Build on PR

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
        - uses: actions/setup-node@v3
          with:
            node-version: '20'

        - name: Build Node
          run: make build-npm

        - name: Test Node
          run: make test-npm

        - name: Build and Test
          run:  mvn clean install jacoco:prepare-agent package jacoco:report
