name: HC e2e-healthy-cameras

on: push

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-isolated-action

      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-isolated-action

      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-isolated-action

      - name: Run Cypress
        run: make cypress-firefox
        continue-on-error: true

  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-isolated-action

      - name: Run Cypress
        run: make cypress-edge
