name: HC Build on PR

on:
  pull_request:
    branches: 
      - '**'
      - 'main'
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'
        - uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Build Node
          run: make build-npm

        - name: Test Node
          run: make test-npm

        - name: Build and Test
          run:  mvn clean install jacoco:prepare-agent package jacoco:report
